### ISSUE TITLE
remote connect question.

### ISSUE THREAD

**Issue by BabelQwerty** [maxDcb/C2TeamServer#1]
how to work with remote connect ?
i use TeamServer in kali , client.py in windows , found can not connect.

**Comment by maxDcb** [comment]
Hello,
Indeed, it was not implemented. I add it in this [commit](https://github.com/maxDcb/C2TeamServer/commit/8d1afb1a8eb0a0de4abd80576c26327731ac66e4). I created a new release 0.0.1 that include this feature.
You can now launch:

`
python GUI.py --ip <TeamServer IP> --dev
`

The --dev is to ignore the hostname that is store in the SSL certificat for the GRPC connection, as the default certificat is created with localhost.

Tell me if it fix you issue.

**Comment by BabelQwerty** [comment]
it work  ,thanks.
