### ISSUE TITLE
Graph.py killing UI when listener is there

### ISSUE THREAD

**Issue by almounah** [maxDcb/C2TeamServer#9]
![image](https://github.com/user-attachments/assets/73150549-a613-4fa8-b1cb-ea7a94b90994)

To reproduce, Create a Listener, then Open the Graph tab in the UI.

Need investigation to check root cause.

**Comment by maxDcb** [comment]
You didn't used the last version of the GRPC messaging for your client. You need to cmake again to regenerate the python messaging system and then it should work.

**Comment by almounah** [comment]
Haha my mistake 🙃
